---
title: "Evaluate testing data (binary-class) - XGBoost"
author: "John Doe"
date: '`r Sys.Date()`'
output:
  pdf_document:
    toc: yes
    toc_depth: '3'
---

Labels: 
  0: Basal
  1: LumA


```{r}
## user input
project_home <- "~/EVE/examples"
project_name <- "xgboost_binary_outCV_test"
```

## 0. Load Data
```{r, warning=FALSE, message=FALSE, echo=FALSE}
library(tidyverse)
library(broom)
library(caret)
library(pROC)
library(ggrepel)
source("~/EVE/eve/reports/utils/PerformanceUtils.R")
load(paste0(project_home,"/log/", project_name, "/metainfo.Rdata"))

if(grepl("\\.r$|\\.R$", runSpec$engine)){
  df.preval <- getResults(project_home, project_name, "rdata", objName = "df_pred")
  df.vimp   <- getResults(project_home, project_name, "rdata", objName = "df_vimp")
} else {
  df.preval <- getResults(project_home, project_name, "prevalidation")
  df.vimp   <- getResults(project_home, project_name, "vimp")
}

## get original data info
df.orig <- read_csv(paste(project_home, runSpec$training_data, sep="/"))

tot.sample <- dim(df.orig)[1]
tot.feature <- max(df.preval$size)
num.cv <- length(unique(df.preval$cv))
num.seed <- length(unique(df.preval$seed))

cat(tot.sample, "of samples were used \n")
cat(tot.feature, "of full features\n")
cat(num.seed, "runs, each run contains", num.cv, "CVs.\n")
cat("Labels:\n")
table(df.orig[[runSpec$label_name]])
```


## 1. Scores

### 1.1 Scores per Class

```{r, fig.width=8, fig.height=6, echo=FALSE, message=FALSE, warning=FALSE}
plt <- plotScores(df.preval, runSpec$label_name)
plt$byClass +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_y_continuous(breaks = seq(0, 1, 0.05))
```

Confusion Matrix
```{r, echo=FALSE}
confusionMat(df.preval)
```

### 1.2 Average score

```{r, echo=FALSE}
plt$overall +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r, warning=FALSE, echo=FALSE}
knitr::kable(eval.minmax(plt$df.scores), digits = 3)
```


## 2. Important Features

```{r, message=FALSE, echo=FALSE, warning=FALSE}
df.vimp.plt <- plotVIMP(df.vimp, bin = 50)
df.vimp.avg <- df.vimp.plt$df

## plot
df.vimp.plt$plt.dist.f
df.vimp.plt$plt.fts.f
df.vimp.plt$plt.dist.g
df.vimp.plt$plt.fts.g

write_csv(df.vimp.avg, paste0(runSpec$outP, "/Analyzed_FeatureImportance_avg.csv"))
```

```{r, echo=FALSE, fig.height=8, fig.width=9}
## vimp scatter plot
plotVIMP_scatter(df.vimp, top_n = 20)
```


```{r, fig.width=8, echo=FALSE}
library(pheatmap)
plotHeatmap(df.vimp.plt$df, df.orig)
```

## 3. Hyper-parameters

```{r, message=FALSE, echo=FALSE}
df.grid <- getResults(project_home, project_name, "grid")
plotGridS(df.grid)
```






