---
title: "Evaluate testing data (regression) - Lasso"
author: "John Doe"
date: '`r Sys.Date()`'
output:
  pdf_document:
    toc: yes
    toc_depth: '3'
---

Labels: os_time


```{r}
## user input
project_home <- "~/EVE/examples"
project_name <- "lasso_regression_outCV_test"
```

## 0. Load Data
```{r, warning=FALSE, message=FALSE, echo=FALSE}
library(tidyverse)
library(broom)
library(caret)
library(pROC)
source("~/EVE/eve/reports/utils/PerformanceUtils.R")
load(paste0(project_home,"/log/", project_name, "/metainfo.Rdata"))

if(grepl("\\.r$|\\.R$", runSpec$engine)){
  df.preval <- getResults(project_home, project_name, "rdata", objName = "df_pred")
  df.vimp   <- getResults(project_home, project_name, "rdata", objName = "df_vimp")
} else {
  df.preval <- getResults(project_home, project_name, "prevalidation")
  df.vimp   <- getResults(project_home, project_name, "vimp")
}

## get original data info
df.orig <- read_csv(paste(project_home, runSpec$training_data, sep="/"))

tot.sample <- dim(df.orig)[1]
tot.feature <- max(df.preval$size)
num.cv <- length(unique(df.preval$cv))
num.seed <- length(unique(df.preval$seed))

cat(tot.sample, "of samples were used \n")
cat(tot.feature, "of full features\n")
cat(num.seed, "runs, each run contains", num.cv, "CVs.\n")
cat(runSpec$label_name, ":\n")
summary(df.orig[[runSpec$label_name]])
```


## 1. Scores

```{r, fig.width=6, fig.height=6, echo=FALSE, message=FALSE, warning=FALSE}
plt <- plotRMSE(df.preval, label_name = runSpec$label_name)
plt$overall +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
```

'Pred' compares the actual CV prediction with observed value. 'Rand' compares permuted CV prediction with observed to mimic random prediction.

### correlation

```{r, echo=FALSE}
correlation(df.preval)
```


## 2. Important Features

```{r, message=FALSE, echo=FALSE, warning=FALSE}
main <- paste('distribution across', length(unique(df.vimp$seed)), 'seed x', length(unique(df.vimp$cv)),'CV')
xlab <- paste('# of times a feature is selected by lasso (alpha=', runSpec$alpha,')')
hist(table(df.vimp$feature), main = main , xlab = xlab)
```

```{r, fig.height=6, echo=FALSE}
par(mar=c(5,20,4,2))
barplot(tail(sort(table(df.vimp$feature)), 20), 
        horiz =T, las=2, main='Number of times a feature is used')
```
(currently only Lasso has this graph)


```{r, echo=FALSE}
df.vimp.plt <- plotVIMP2(df.vimp, bin = 100, top_n = 20)
## plot
df.vimp.plt$plt.dist.f +
  ggtitle("Distribution of Feature Coefficient")
df.vimp.plt$plt.fts.f +
  ggtitle("Top Features")
```

```{r, fig.width=8, echo=FALSE}
library(pheatmap)
plotHeatmap(df.vimp.plt$df, df.orig)
```


